name = mob_spawn_panel
title = Mob Spawn Panel
description = Painel formspec (/bichos, /monstros) pra invocar animais e monstros/dragoes sem precisar digitar /spawnentity.
depends = animalia, mobs_monster, dmobs
