services:
  luanti:
    build: .
    container_name: mineleo-luanti
    restart: unless-stopped
    ports:
      - "30000:30000/udp"
    volumes:
      - ./minetest.conf:/luanti/minetest.conf
      - ./world:/luanti/world
      - ./mods:/luanti/mods
